### ISSUE TITLE
Kernel does not boot properly

### ISSUE THREAD

**Issue by KubotaAtSeltech** [avionic-design/linux-l4t#1]
Kernel does not boot properly. Is there a mistake in the procedure something?

1) Download the kernel and  make uImage.

<pre>
HOST-PC $ git clone https://github.com/avionic-design/linux-l4t.git  kernel/linux-avionic.git
HOST-PC $ cd kernel/linux-avionic.git
HOST-PC $ git checkout tamonten/l4t-r16-3
HOST-PC $ make tegra_tec_ng_defconfig
HOST-PC $ make -j4 uImage
</pre>

2) Download tftpboot using the u-boot, I started to kernel

<pre>
Tegra30 (TEC-NG) # bootm
## Booting kernel from Legacy Image at 80408000 ...
   Image Name:   Linux-3.1.10-tec-ng+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3477168 Bytes = 3.3 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
<6>Initializing cgroup subsys cpu
<5>Linux version 3.1.10-tec-ng+ (teka@teka-ThinkPad-T60) (gcc version 4.4.1 (Sourcery G++
Lite 2009q3-67) ) #1 SMP
 PREEMPT Wed Oct 23 12:45:16 JST 2013
CPU: ARMv7 Processor [412fc099] revision 9 (ARMv7), cr=10c5387d
CPU: VIPT nonaliasing data cache, VIPT aliasing instruction cache
Machine: tec_ng
<6>Tegra reserved memory:
LP0:                     00000000 - 00000000
Bootloader framebuffer:  00000000 - 00000000
Bootloader framebuffer2: 00000000 - 00000000
Framebuffer:             b6800000 - b6ffffff
2nd Framebuffer:         b7000000 - b77fffff
Carveout:                b8000000 - bfffffff
Vpr:                     00000000 - 00000000
Memory policy: ECC disabled, Data cache writealloc
<7>On node 0 totalpages: 225024
<7>free_area_init_node: node 0, pgdat c069ab00, node_mem_map c0809000
<7>  Normal zone: 1728 pages used for memmap
<7>  Normal zone: 0 pages reserved
<7>  Normal zone: 194880 pages, LIFO batch:31
<7>  HighMem zone: 576 pages used for memmap
<7>  HighMem zone: 27840 pages, LIFO batch:7
<6>fuse_speedo_calib: ATE prog ver 4.0
<6>Tegra3: CPU Speedo ID 2, Soc Speedo ID 2<6>Tegra Revision: A03 SKU: 0xb1 CPU Process: 3
Core Process: 0
<6>tegra: PLLP fixed rate: 408000000
<4>Lowering cpu_lp maximum rate from 620000000 to 513000000
<4>Lowering sbus maximum rate from 378000000 to 267000000
<4>Lowering vi maximum rate from 470000000 to 409000000
<4>Lowering vde maximum rate from 600000000 to 437000000
<4>Lowering mpe maximum rate from 600000000 to 446000000
<4>Lowering 2d maximum rate from 600000000 to 446000000
<4>Lowering epp maximum rate from 600000000 to 446000000
<4>Lowering 3d maximum rate from 600000000 to 446000000
<4>Lowering 3d2 maximum rate from 600000000 to 446000000
<4>Lowering se maximum rate from 625000000 to 446000000
<4>Lowering host1x maximum rate from 300000000 to 267000000
<4>Lowering cbus maximum rate from 700000000 to 437000000
<4>Lowering pll_c maximum rate from 1400000000 to 1066000000
<4>Lowering ndflash maximum rate from 240000000 to 200000000
<4>Lowering sbc1 maximum rate from 160000000 to 100000000
<4>Lowering sbc2 maximum rate from 160000000 to 100000000
<4>Lowering sbc3 maximum rate from 160000000 to 100000000
<4>Lowering sbc4 maximum rate from 160000000 to 100000000
<4>Lowering sbc5 maximum rate from 160000000 to 100000000
<4>Lowering sbc6 maximum rate from 160000000 to 100000000
<4>Lowering dsia maximum rate from 500000000 to 432500000
<4>Lowering dsib maximum rate from 500000000 to 432500000
<4>Lowering cpu_g maximum rate from 1700000000 to 1350000000
<4>tegra3_dvfs: cold offset 50000000 is too high for regular dvfs limit 1000000
<4>tegra3_dvfs: cold offset 50000000 is too high for regular dvfs limit 1000000
<4>tegra3_dvfs: cold offset 50000000 is too high for regular dvfs limit 1000000
<4>tegra3_dvfs: cold offset 50000000 is too high for regular dvfs limit 1000000
<6>tegra dvfs: VDD_CPU nominal 1087mV, scaling enabled
<6>tegra dvfs: VDD_CORE nominal 1200mV, scaling enabled
<4>tegra_dvfs: voltage 1300 too high for dvfs on emc
<4>Unable to enable clock emc: -22
<4>tegra_dvfs: voltage 1100 too high for dvfs on cpu_g
<4>Unable to enable clock cpu: -22
</pre>

**Comment by soerengrunewald** [comment]
You have triggered a known power-management issue, we are currently working on. You can workaround this issue by adding the following kernel boot parameter: **core_edp_mv=1300**

**Comment by KubotaAtSeltech** [comment]
Kernel was able to boot.
