### ISSUE TITLE
initrd and rootfs build failed

### ISSUE THREAD

**Issue by sijo-mathew** [avionic-design/linux-l4t#2]
While building the platform, it looks like hanged and no more compiling. Same error is coming while building initrd and rootfs.  The following is the last few lines of build log.

I followed exactly same steps given in the following link
https://github.com/avionic-design/pbs-stage2/blob/master/Documentation/ubuntu-howto

The details of host PC I am trying to run is
Linux 3.8.0-33-generic #48~precise1-Ubuntu SMP Thu Oct 24 16:31:16 UTC 2013 i686 i686 i386 GNU/Linux
## log details

cd /home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/bin && ln -s -f vapicheck-0.18 vapicheck
make[6]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
 /bin/mkdir -p '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/aclocal'
 /usr/bin/install -c -m 644 ../../vapigen/vapigen.m4 '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/aclocal'
 /bin/mkdir -p '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/vala'
 /usr/bin/install -c -m 644 ../../vapigen/Makefile.vapigen '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/vala'
 /bin/mkdir -p '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/pkgconfig'
 /usr/bin/install -c -m 644 vapigen-0.18.pc '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/pkgconfig'
/usr/bin/make  install-data-hook
make[6]: Entering directory`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
cd /home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/pkgconfig && ln -s -f vapigen-0.18.pc vapigen.pc
make[6]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
make[5]: Leaving directory`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
make[4]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
make[3]: Leaving directory`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
make[2]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu/vapigen'
make[2]: Entering directory`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu'
make[3]: Entering directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu'
make[3]: Nothing to be done for`install-exec-am'.
 /bin/mkdir -p '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/aclocal'
 /usr/bin/install -c -m 644 ../vala.m4 '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/share/aclocal'
 /bin/mkdir -p '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/lib/pkgconfig'
 /usr/bin/install -c -m 644 libvala-0.18.pc '/home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/lib/pkgconfig'
make[3]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu'
make[2]: Leaving directory`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu'
make[1]: Leaving directory `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/vala-0.18.1/obj-i686-pc-linux-gnu'
  STAMP   /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/.do-install
  PRUNE   /home/ubuntu/devel/pbs-stage2/build/rootfs/build-tools/lib/libvala-0.18.la
  STAMP   /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/.prune
  STAMP   /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/.binary
  STAMP   /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/build-tools/vala/.install
  SHA1    /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/kernel/kmod.hash
  SHA1    /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/devel/glibc.hash
  SHA1    /home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/devel/gcc-libs.hash
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory
/home/ubuntu/devel/pbs-stage2/packages/devel/gcc-libs/Makefile:58: warning: overriding commands for target`/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/devel/gcc-libs/install/usr/include/c++'
/home/ubuntu/devel/pbs-stage2/packages/devel/gcc-libs/Makefile:55: warning: ignoring old commands for target `/home/ubuntu/devel/pbs-stage2/build/rootfs/build/packages/devel/gcc-libs/install/usr/include/c++'
env: armv7l-unknown-linux-gnueabihf-gcc: No such file or directory

**Comment by julianscheel** [comment]
This bug-report should be in pbs-stage2 project. This is the kernel repository only.
Please see this issue: https://github.com/avionic-design/pbs-stage2/issues/5
You seem to be running in the same. You built a softftp toolchain (see the NOTE in the toolchain section of the howto), but the platform you try to build is configured for hardfp.
So either change the platform to softftp as described in the linked issue, or build a hardfp toolchain with pbs-stage1.

If the issue persists, please reopen in pbs-stage2 project.

**Comment by AlbanBedel** [comment]
I would suggest adding a check for the toolchain before starting the build. This way if the tollchain is not available we could have a clear error message instead of a cryptic failure while building some package.
